suppressMessages(library(dplyr))
suppressMessages(library(gap))
suppressMessages(library(lars))
suppressMessages(library(openxlsx))
p <- Sys.getenv("p")
pr <- Sys.getenv("pr")
r <- scan(paste0("results/",pr,".jma"),"")
cma <- read.delim(paste0("results/",pr,".gcta.cma.cojo"))
jma <- read.delim(paste0("results/",pr,".gcta.jma.cojo"))
ldr <- read.delim(paste0("results/",pr,".gcta.ldr.cojo"))
rownames(ldr) <- ldr[["SNP"]]
ldr <- ldr[,2:(nrow(ldr)+1)]
ld <- read.table(paste0("results/",pr,".ld"),col.names=rownames(ldr),row.names=rownames(ldr))
xlsx <- paste0("results/",pr,".xlsx")
wb <- createWorkbook(xlsx)
addWorksheet(wb, "jma")
writeDataTable(wb, "jma", jma)
addWorksheet(wb, "ldr")
writeDataTable(wb, "ldr", ldr, rowNames=TRUE)
addWorksheet(wb, "cma")
writeDataTable(wb, "cma", cma)
addWorksheet(wb, "ld")
writeDataTable(wb, "ld", ld, rowNames=TRUE)
saveWorkbook(wb, file=xlsx, overwrite=TRUE)
raw <- read.delim(paste0("results/",pr,".dosage.raw")) %>% select(-FID, -PAT, -MAT, -SEX, -PHENOTYPE)
load("reports/edata_batch.rda")
load("data/pheno.rda")
edata <- with(edata_batch,edata)
edata[,p] <- invnormal(edata[,p])
xp <- gsub("^([0-9])","X\\1",p)
edata <- left_join(subset(id,!is.na(IID)),data.frame(caprion_id=rownames(edata),edata)) %>%
select(IID,all_of(xp)) %>%
left_join(raw) %>%
select(-IID)
names(edata) <- gsub("^X([0-9])","\\1",names(edata))
dosage <- select(edata,-all_of(p))
names(dosage) <- unlist(lapply(strsplit(names(dosage),"_"),"[",1))
r <- gsub(":",".",unlist(lapply(strsplit(r,"_"),"[",1)))
all <- lm(edata[[p]] ~ ., data=dosage[r])
print(anova(all))
print(summary(all))
m <- as.matrix(subset(edata,!is.na(edata[[p]])))
fit <- lars(m,edata[[p]][!is.na(edata[[p]])],type="lasso")
print(fit)
